@host=http://localhost:5084

GET {{host}}/properties
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyNzEwYWY3Ni0yNGZmLTRiNjktYWViYi1lMzBhNTljNmEyMjYiLCJnaXZlbl9uYW1lIjoiTWFybmkiLCJmYW1pbHlfbmFtZSI6IkZhbGt2YXJkIEpvZW5zZW4iLCJqdGkiOiJiZjEyMmY4Ny03ZGQ1LTQyNmEtYWM5Yi02NTcxMDliMWIzNjUiLCJleHAiOjE2OTk3OTY3NDcsImlzcyI6IlByb3BlcnR5QXBpIiwiYXVkIjoiUHJvcGVydHlBcGkifQ.hG2e9vKzESt5tWza51FCxUzfjC8tNtFGlCqQ-rBEjHI