@host=http://localhost:5084

GET {{host}}/properties
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhYjRjMjk1NC03OWQyLTRjOGUtOTBlNS1iOTJhYTVlNTIwMjEiLCJnaXZlbl9uYW1lIjoiTWFybmkiLCJmYW1pbHlfbmFtZSI6IkZhbGt2YXJkIEpvZW5zZW4iLCJqdGkiOiIwMTMwOWJiNi1mOTkxLTQ5MDktOGEwZS0zODJhYTJmOGUwMGQiLCJleHAiOjE2OTk3OTc3NTYsImlzcyI6IlByb3BlcnR5QXBpIiwiYXVkIjoiUHJvcGVydHlBcGkifQ.FZjr4VohPo-EJ20Zikv2D7FEhahb2b5u2z1G6pvEOjw